name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.12"]

        permissions: 
            contents: read
            packages: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{matrix.python-version}}

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Lint
              run: ruff check .
            
            - name: Run tests with coverage
              run: pytest --cov=. --cov-report=term-missing

            - name: Build Docker image
              if: matrix.python-version == '3.12' && github.event_name == 'push'
              run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

            - name: Login to ghcr
              if: matrix.python-version == '3.12' && github.event_name == 'push'
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Push Docker image 
              if: matrix.python-version == '3.12' && github.event_name == 'push'
              run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
      
    deploy:
        needs: test
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to EC2
              uses: appleboy/ssh-action@v1.2.5
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      NEW_IMAGE=ghcr.io/${{ github.repository }}:${{ github.sha }}
                      STATE_FILE=/opt/ci-cd-learning/current_image

                      echo "New_image: $NEW_IMAGE"
                      if [ -f "$STATE_FILE" ]; then
                          OLD_IMAGE=$(cat $STATE_FILE)
                          echo "Previous_image: $OLD_IMAGE"
                      else
                          echo "No Previous_image found. This is the first deployment."
                          OLD_IMAGE=""
                      fi

                      docker pull $NEW_IMAGE
                      docker stop ci-cd-app || true
                      docker rm ci-cd-app || true
                      docker run -d \
                        --name ci-cd-app \
                        --restart unless-stopped \
                        -p 8000:8000 \
                        $IMAGE

                      echo "Waiting for application to become healthy..."

                      HEALTHY=false
                      
                      for i in {1..10}; do
                          if curl -fs http://localhost:8000/health; then
                              echo "Application is healthy"
                              HEALTHY=true
                              break
                          fi

                          echo "Health check failed. Retrying in 2 seconds..."
                              sleep 2
                      done

                      if [ "$HEALTHY" = true ]; then
                          echo "Application is healthy"
                          echo "$NEW_IMAGE" > "$STATE_FILE"
                          exit 0
                      fi

                      echo "Application failed health check"
                      docker logs ci-cd-app

                      # ROLLBACK
                      if [ -n "$OLD_IMAGE" ]; then
                          echo "Rolling back to previous image: $OLD_IMAGE"
                          docker stop ci-cd-app || true
                          docker rm ci-cd-app || true
                          docker run -d \
                            --name ci-cd-app \
                            --restart unless-stopped \
                            -p 8000:8000 \
                            "$OLD_IMAGE"

                          echo "Waiting for application to become healthy after rollback..."

                          for i in {1..10}; do
                              if curl -fs http://localhost:8000/health; then
                                  echo "Rollback successful"
                                  exit 1
                              fi
                              
                              sleep 2
                          done

                          echo "Rollback failed."
                          docker logs ci-cd-app ||
                          exit 1
                        fi

                        echo "No previous image to rollback to. Deployment failed."
                      exit 1
