name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.12"]

        permissions: 
            contents: read
            packages: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{matrix.python-version}}

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Lint
              run: ruff check .
            
            - name: Run tests with coverage
              run: pytest --cov=. --cov-report=term-missing

            - name: Build Docker image
              if: matrix.python-version == '3.12' && github.event_name == 'push'
              run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

            - name: Login to ghcr
              if: matrix.python-version == '3.12' && github.event_name == 'push'
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Push Docker image 
              if: matrix.python-version == '3.12' && github.event_name == 'push'
              run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
      
    deploy:
        needs: test
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to EC2
              uses: appleboy/ssh-action@v1.2.5
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      NEW_IMAGE=ghcr.io/${{ github.repository }}:${{ github.sha }}

                      echo "New_image: $NEW_IMAGE"
                      echo "Pulling new image: $NEW_IMAGE"

                      docker pull $NEW_IMAGE
                      docker stop ci-cd-app-new || true
                      docker rm ci-cd-app-new || true
                      docker run -d \
                        --name ci-cd-app-new \
                        --restart unless-stopped \
                        -p 8001:8000 \
                        $NEW_IMAGE

                      echo "Waiting for application to become healthy..."

                      HEALTHY=false
                      
                      for i in {1..10}; do
                          if curl --fail http://localhost:8001/health; then
                              HEALTHY=true
                              break
                          fi

                          echo "Health check failed. Retrying in 2 seconds..."
                              sleep 2
                      done

                      if [ "$HEALTHY" != true ]; then
                          echo "Application failed health check"
                          echo "Candidate container logs:"
                          docker logs ci-cd-app-new || true

                          docker stop ci-cd-app-new || true
                          docker rm ci-cd-app-new || true
                          exit 1
                      fi

                      echo "New version is healthy. Proceeding with deployment."

                      docker stop ci-cd-app || true
                      docker rm ci-cd-app || true

                      echo "Starting new version of the application..."
                      docker run -d \
                        --name ci-cd-app \
                        --restart unless-stopped \
                        -p 8000:8000 \
                        $NEW_IMAGE

                      Healthy=false
                      for i in {1..10}; do
                          if curl --fail http://localhost:8000/health; then
                              Healthy=true
                              break
                          fi
                          echo "Health check failed. Retrying in 2 seconds..."
                          sleep 2
                      done

                      if [ "$HEALTHY" != true ]; then
                          echo "Application failed health check"
                          docker logs ci-cd-app || true
                          exit 1
                      fi

                      echo "Deployment successful. Cleaning up old containers..."
                          docker stop ci-cd-app-new || true
                          docker rm ci-cd-app-new || true